### ISSUE TITLE
Resume torrents on browser restart

### ISSUE THREAD

**Issue by retrohacker** [retrohacker/peerweb2.0#15]
Persist webtorrent state between invocations of peerweb.

**Comment by phoenix1796** [comment]
I think this might help (look at it's closing commit for details)
https://github.com/feross/webtorrent-desktop/issues/24

**Comment by retrohacker** [comment]
Yes, it does help. We need to implement https://github.com/electron/electron/blob/master/docs/api/app.md#appmakesingleinstancecallback if we are going to persist to a file though.

**Comment by retrohacker** [comment]
Looking to upstream a lot of this work here: https://github.com/feross/webtorrent/issues/872

Depending on the work there, we should be able to wire up `client.on('state'` to [`config.write`](https://github.com/LinusU/node-application-config) and then load that state when the application starts back up.
