### ISSUE TITLE
PeerWeb UI missing window controls

### ISSUE THREAD

**Issue by tumland** [retrohacker/peerweb2.0#21]
PeerWeb browser UI should have standard OS window controls - close, minimize, maximize.

Otherwise, closing the window(s) has to be done by killing the app.

**Comment by retrohacker** [comment]
:+1:

**Comment by retrohacker** [comment]
Sorry, wrong button.

**Comment by retrohacker** [comment]
This should be solved as of https://github.com/retrohacker/peerweb/pull/27
