### ISSUE TITLE
PeerWeb should use the 'standard' linting tool

### ISSUE THREAD

**Issue by tumland** [retrohacker/peerweb2.0#23]
I believe WebTorrent uses the JavaScript linter called 'standard', also created by @feross. 

For consistency, I think it makes sense for PeerWeb to follow similar coding style. Standard tool will help.

**Comment by retrohacker** [comment]
We are using Standard :smile:

It isn't opinionated enough IMO so I layer on the airbnb style guide to fill in the gaps.

**Comment by retrohacker** [comment]
https://github.com/retrohacker/peerweb/blob/master/.eslintrc.json#L7
