### ISSUE TITLE
Please, consider to specify a license

### ISSUE THREAD

**Issue by ifraixedes** [retrohacker/peerweb2.0#33]
First of all, thanks to release this work on a public repository.

Nonetheless, this repo doesn't have any concrete license (or it isn't easy to see), so I would like that you consider to choose one to avoid the confusion that it causes with its absence, the work has applied the default copyright laws which the most of the people we aren't sure the implications because we aren't lawyers.

[This page may help you to decide which one is more convenient for you and all the benefits that an open license has over a closed one](https://help.github.com/articles/open-source-licensing/), however, don't get me wrong, choose the one that fits better to your specific case, independently if it's open or not.

If the project is in an early stage and you want to postpone the decision, please consider adding a note in the README or another kind of signal about this matter.

Thanks so much for considering.

**Comment by retrohacker** [comment]
Oh my, this was a massive oversight on my part. Thank you for opening an issue. My projects are all under MIT unless stated otherwise. Updating repo now :smile:
